/home/ul/ul_student/ul_swc81/.conda/envs/cvproj/bin/python: can't open file '/var/spool/slurmd/job21430269/train.py': [Errno 2] No such file or directory
/home/ul/ul_student/ul_swc81/.conda/envs/cvproj/bin/python: can't open file '/var/spool/slurmd/job21430269/train.py': [Errno 2] No such file or directory
/home/ul/ul_student/ul_swc81/.conda/envs/cvproj/bin/python: can't open file '/var/spool/slurmd/job21430269/train.py': [Errno 2] No such file or directory
/home/ul/ul_student/ul_swc81/.conda/envs/cvproj/bin/python: can't open file '/var/spool/slurmd/job21430269/train.py': [Errno 2] No such file or directory
/home/ul/ul_student/ul_swc81/.conda/envs/cvproj/bin/python: can't open file '/var/spool/slurmd/job21430269/train.py': [Errno 2] No such file or directory
/home/ul/ul_student/ul_swc81/.conda/envs/cvproj/bin/python: can't open file '/var/spool/slurmd/job21430269/train.py': [Errno 2] No such file or directory
/home/ul/ul_student/ul_swc81/.conda/envs/cvproj/bin/python: can't open file '/var/spool/slurmd/job21430269/train.py': [Errno 2] No such file or directory
/home/ul/ul_student/ul_swc81/.conda/envs/cvproj/bin/python: can't open file '/var/spool/slurmd/job21430269/train.py': [Errno 2] No such file or directory
/home/ul/ul_student/ul_swc81/.local/lib/python3.8/site-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 326203) of binary: /home/ul/ul_student/ul_swc81/.conda/envs/cvproj/bin/python
Traceback (most recent call last):
  File "/home/ul/ul_student/ul_swc81/.conda/envs/cvproj/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ul/ul_student/ul_swc81/.conda/envs/cvproj/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ul/ul_student/ul_swc81/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/home/ul/ul_student/ul_swc81/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/home/ul/ul_student/ul_swc81/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/home/ul/ul_student/ul_swc81/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/ul/ul_student/ul_swc81/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ul/ul_student/ul_swc81/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/var/spool/slurmd/job21430269/train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-12-19_20:03:13
  host      : uc2n510.localdomain
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 326204)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-12-19_20:03:13
  host      : uc2n510.localdomain
  rank      : 2 (local_rank: 2)
  exitcode  : 2 (pid: 326205)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2022-12-19_20:03:13
  host      : uc2n510.localdomain
  rank      : 3 (local_rank: 3)
  exitcode  : 2 (pid: 326206)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2022-12-19_20:03:13
  host      : uc2n510.localdomain
  rank      : 4 (local_rank: 4)
  exitcode  : 2 (pid: 326207)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2022-12-19_20:03:13
  host      : uc2n510.localdomain
  rank      : 5 (local_rank: 5)
  exitcode  : 2 (pid: 326208)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2022-12-19_20:03:13
  host      : uc2n510.localdomain
  rank      : 6 (local_rank: 6)
  exitcode  : 2 (pid: 326209)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2022-12-19_20:03:13
  host      : uc2n510.localdomain
  rank      : 7 (local_rank: 7)
  exitcode  : 2 (pid: 326210)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-12-19_20:03:13
  host      : uc2n510.localdomain
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 326203)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

============================= JOB FEEDBACK =============================

NodeName=uc2n510
Job ID: 21430269
Cluster: uc2
User/Group: ul_swc81/ul_student
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 48
CPU Utilized: 00:00:03
CPU Efficiency: 0.07% of 01:14:24 core-walltime
Job Wall-clock time: 00:01:33
Memory Utilized: 197.85 MB
Memory Efficiency: 0.00% of 0.00 MB
